--
-- Файл сгенерирован с помощью SQLiteStudio v3.4.17 в пн янв. 12 07:44:58 2026
--
-- Использованная кодировка текста: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: AccountEvents
DROP TABLE IF EXISTS AccountEvents;
CREATE TABLE IF NOT EXISTS AccountEvents (acc_events_id INTEGER PRIMARY KEY, event_date DATE, event_time TIME, account_id INTEGER REFERENCES Accounts (accounts_id), event_id INTEGER REFERENCES Events (event_id), tool_id INTEGER REFERENCES Tools (tool_id), tool_code TEXT, tool_price REAL, tool_count INTEGER, NDK REAL, broker_fee REAL, birga_fee REAL, bound REAL, dividend REAL, tax REAL);

-- Таблица: Accounts
DROP TABLE IF EXISTS Accounts;
CREATE TABLE IF NOT EXISTS Accounts (accounts_id INTEGER PRIMARY KEY, accounts_bank INTEGER REFERENCES Banks (bank_id), accounts_type INTEGER REFERENCES AccountTypes (account_type_id), accounts_number TEXT);

-- Таблица: AccountTypes
DROP TABLE IF EXISTS AccountTypes;
CREATE TABLE IF NOT EXISTS AccountTypes (account_type_id INTEGER PRIMARY KEY, account_type TEXT);

-- Таблица: Agency
DROP TABLE IF EXISTS Agency;
CREATE TABLE IF NOT EXISTS Agency (id_agency INTEGER PRIMARY KEY, agency_full_name TEXT, agency_short_name TEXT, agency_site TEXT);

-- Таблица: Banks
DROP TABLE IF EXISTS Banks;
CREATE TABLE IF NOT EXISTS Banks (bank_id INTEGER PRIMARY KEY, bank_name TEXT);

-- Таблица: Boardgroups
DROP TABLE IF EXISTS Boardgroups;
CREATE TABLE IF NOT EXISTS Boardgroups (id INTEGER PRIMARY KEY, engine_id INTEGER REFERENCES Engines (engine_id), market_id INTEGER, name TEXT (192), title TEXT (765), is_default BOOLEAN, board_group_id INTEGER, is_traded INTEGER, is_order_driven INTEGER, category_id INTEGER REFERENCES Category (category_id));

-- Таблица: Boards
DROP TABLE IF EXISTS Boards;
CREATE TABLE IF NOT EXISTS Boards (id INTEGER PRIMARY KEY, board_group_id INTEGER, engine_id INTEGER REFERENCES Engines (engine_id), market_id INTEGER REFERENCES Markets (market_id), board_id TEXT (12), board_title TEXT (381), is_traded BOOLEAN, has_candles BOOLEAN, is_primary BOOLEAN);

-- Таблица: BondDescription
DROP TABLE IF EXISTS BondDescription;
CREATE TABLE IF NOT EXISTS BondDescription (id_description INTEGER PRIMARY KEY, SECID TEXT, ISIN TEXT, INITIALFACEVALUE INTEGER, FACEUNIT TEXT, LISTLEVEL INTEGER, FACEVALUE INTEGER, ISQUALIFIEDINVESTORS INTEGER, EMITTER_ID INTEGER, EMITTER TEXT);

-- Таблица: BondsCollections
DROP TABLE IF EXISTS BondsCollections;
CREATE TABLE IF NOT EXISTS BondsCollections (id INTEGER PRIMARY KEY, SECID TEXT, ISSUENAME TEXT, NAME TEXT, SHORTNAME TEXT, REGNUMBER TEXT, ISIN TEXT, ISSUEDATE DATE, MATDATE DATE, BUYBACKDATE DATE, INITIALFACEVALUE DOUBLE, FACEUNIT TEXT, LATNAME TEXT, STARTDATEMOEX DATE, HASPROSPECTUS INTEGER, ISCONCESSIONAGREEMENT INTEGER, PROGRAMREGISTRYNUMBER TEXT, EMITENTMISMATCHFIRST INTEGER, EMITENTMISMATCHCUR INTEGER, LISTLEVEL INTEGER, INCLUDEDBYMOEX INTEGER, DAYSTOREDEMPTION INTEGER, ISSUESIZE INTEGER, FACEVALUE DOUBLE, ISQUALIFIEDINVESTORS INTEGER, QUALINVESTORGROUP TEXT, COUPONFREQUENCY INTEGER, COUPONDATE DATE, COUPONPERCENT DOUBLE, COUPONVALUE DOUBLE, ISSUESIZEPLANNED INTEGER, SECSUBTYPE TEXT, MORNINGSESSION INTEGER, EVENINGSESSION INTEGER, WEEKENDSESSION TEXT, HIGHRISK INTEGER, REGISTRY_DATE TEXT, BOND_TYPE TEXT, BOND_SUBTYPE TEXT, TYPE TEXT, TYPENAME TEXT, IS_TRADED INTEGER, UPDATED_AT DATETIME);

-- Таблица: BondsMarketData
DROP TABLE IF EXISTS BondsMarketData;
CREATE TABLE IF NOT EXISTS BondsMarketData (id INTEGER PRIMARY KEY, SECID TEXT, BOARDID TEXT, PRICE DOUBLE, YIELDDATE DATE, ZCYCMOMENT DATETIME, YIELDDATETYPE TEXT, EFFECTIVEYIELD DOUBLE, DURATION INTEGER, ZSPREADBP INTEGER, GSPREADBP INTEGER, WAPRICE DOUBLE, EFFECTIVEYIELDWAPRICE DOUBLE, DURATIONWAPRICE INTEGER, IR DOUBLE, ICPI DOUBLE, BEI DOUBLE, CBR DOUBLE, YIELDTOOFFER DOUBLE, YIELDLASTCOUPON DOUBLE, TRADEMOMENT DATETIME, SEQNUM INTEGER, SYSTIME DATETIME);

-- Таблица: BondsSecurities
DROP TABLE IF EXISTS BondsSecurities;
CREATE TABLE IF NOT EXISTS BondsSecurities (id INTEGER PRIMARY KEY, SECID TEXT, BOARDID TEXT, SHORTNAME TEXT, PREVWAPRICE DOUBLE, YIELDATPREVWAPRICE DOUBLE, COUPONVALUE DOUBLE, NEXTCOUPON DATE, ACCRUEDINT DOUBLE, PREVPRICE DOUBLE, LOTSIZE INTEGER, FACEVALUE DOUBLE, BOARDNAME TEXT, STATUS TEXT, MATDATE DATE, DECIMALS INTEGER, COUPONPERIOD INTEGER, ISSUESIZE INTEGER, PREVLEGALCLOSEPRICE DOUBLE, PREVDATE DATE, SECNAME TEXT, REMARKS TEXT, MARKETCODE TEXT, INSTRID TEXT, SECTORID TEXT, MINSTEP DOUBLE, FACEUNIT TEXT, BUYBACKPRICE DOUBLE, BUYBACKDATE DATE, ISIN TEXT, LATNAME TEXT, REGNUMBER TEXT, CURRENCYID TEXT, ISSUESIZEPLACED INTEGER, LISTLEVEL INTEGER, SECTYPE TEXT, COUPONPERCENT DOUBLE, OFFERDATE DATE, SETTLEDATE DATE, LOTVALUE DOUBLE, FACEVALUEONSETTLEDATE DOUBLE, CALLOPTIONDATE TEXT, PUTOPTIONDATE DATE, DATEYIELDFROMISSUER DATE, BONDTYPE TEXT, BONDSUBTYPE TEXT);

-- Таблица: BoundAmortizations
DROP TABLE IF EXISTS BoundAmortizations;
CREATE TABLE IF NOT EXISTS BoundAmortizations (id_amort INTEGER PRIMARY KEY, SECID TEXT, amort_date DATA, face_value INTEGER, valueprc REAL, amort_value REAL);

-- Таблица: BoundCoupons
DROP TABLE IF EXISTS BoundCoupons;
CREATE TABLE IF NOT EXISTS BoundCoupons (id_coupon INTEGER PRIMARY KEY, SECID TEXT, coupon_date DATE, face_value INTEGER, coupon_value REAL, valueprc REAL);

-- Таблица: Category
DROP TABLE IF EXISTS Category;
CREATE TABLE IF NOT EXISTS Category (category_id INTEGER PRIMARY KEY, category TEXT (45));

-- Таблица: CompanySector
DROP TABLE IF EXISTS CompanySector;
CREATE TABLE IF NOT EXISTS CompanySector (id_company_sector INTEGER PRIMARY KEY, company TEXT, sector INTEGER REFERENCES Sectors (id_sector));

-- Таблица: Durations
DROP TABLE IF EXISTS Durations;
CREATE TABLE IF NOT EXISTS Durations (duration_id INTEGER PRIMARY KEY, interval INTEGER, duration INTEGER, days INTEGER, title TEXT (765), hint TEXT (765));

-- Таблица: Engines
DROP TABLE IF EXISTS Engines;
CREATE TABLE IF NOT EXISTS Engines (engine_id INTEGER PRIMARY KEY, engine_name TEXT (45), engine_title TEXT (765));

-- Таблица: Events
DROP TABLE IF EXISTS Events;
CREATE TABLE IF NOT EXISTS Events (event_id INTEGER PRIMARY KEY, event TEXT);

-- Таблица: Inflation
DROP TABLE IF EXISTS Inflation;
CREATE TABLE IF NOT EXISTS Inflation (Id_period INTEGER PRIMARY KEY, year INTEGER, inflation REAL);

-- Таблица: Issuer
DROP TABLE IF EXISTS Issuer;
CREATE TABLE IF NOT EXISTS Issuer (id_issuer INTEGER PRIMARY KEY, issuer_name TEXT, issuer_form TEXT);

-- Таблица: IssuerDict
DROP TABLE IF EXISTS IssuerDict;
CREATE TABLE IF NOT EXISTS IssuerDict (id_issuer_dict INTEGER PRIMARY KEY, field_index TEXT, field_index_ru TEXT, computing_unit TEXT);

-- Таблица: IssuerRating
DROP TABLE IF EXISTS IssuerRating;
CREATE TABLE IF NOT EXISTS IssuerRating (id_rating INTEGER PRIMARY KEY, id_issuer INTEGER REFERENCES Issuer (id_issuer), rating TEXT, rating_data TEXT, agency INTEGER);

-- Таблица: IssuerReporting
DROP TABLE IF EXISTS IssuerReporting;
CREATE TABLE IF NOT EXISTS IssuerReporting (id_issuer INTEGER PRIMARY KEY, emitter TEXT (10), Report_year INTEGER, Report_date DATE, Report_currency TEXT, Oil_production REAL, Oil_refining REAL, Gas_production REAL, Revenue REAL, Operating_profit REAL, EBITDA REAL, Net_profit REAL, Operating_cash_flow REAL, CAPEX REAL, FCF REAL, Dividend_payout REAL, Dividend REAL, Dividend_income REAL, Dividends_profit REAL, Oper_expenses REAL, Depreciation REAL, Personnel_expenses REAL, Interest_expenses REAL, Assets REAL, Net_assets REAL, Debt REAL, Cash REAL, Net_debt REAL, JSC_share_price REAL, JSC_share_number REAL, Capitalization REAL, EV REAL, Balance_sheet_value REAL, EPS REAL, FCF_share REAL, BV_share REAL, EBITDA_return REAL, Net_return REAL, FCF_yield REAL, ROE REAL, ROA REAL, P_E REAL, P_FCF REAL, P_S REAL, P_BV REAL, EV_EBITDA REAL, Debt_EBITDA REAL, RD_CAPEX REAL, CAPEX_Revenue REAL, Cost_price REAL);

-- Таблица: Markets
DROP TABLE IF EXISTS Markets;
CREATE TABLE IF NOT EXISTS Markets (id INTEGER PRIMARY KEY, engine_id INTEGER REFERENCES Engines (engine_id), market_id INTEGER, market_name TEXT (45), market_title TEXT (765), market_place TEXT (48), is_otc BOOLEAN, has_history_files BOOLEAN, has_history_trades_files BOOLEAN, has_trades BOOLEAN, has_history BOOLEAN, has_candles BOOLEAN, has_orderbook BOOLEAN, has_tradingsession BOOLEAN, has_extra_yields BOOLEAN, has_delay BOOLEAN);

-- Таблица: Portfolio
DROP TABLE IF EXISTS Portfolio;
CREATE TABLE IF NOT EXISTS Portfolio (id_portfolio_tool INTEGER PRIMARY KEY, id_tool INTEGER, id_operarion INTEGER REFERENCES PortfolioOperations (id_operation), tool_code TEXT, date DATE, price REAL, count INTEGER, NKD REAL, brocer_fee REAL, birga_fee REAL);

-- Таблица: ReferenceTable
DROP TABLE IF EXISTS ReferenceTable;
CREATE TABLE IF NOT EXISTS ReferenceTable (reference_id INTEGER PRIMARY KEY, field_name TEXT, field_short_title TEXT, field_full_title TEXT, field_type TEXT);

-- Таблица: SECID
DROP TABLE IF EXISTS SECID;
CREATE TABLE IF NOT EXISTS SECID (SECID_id INTEGER PRIMARY KEY, SECID TEXT);

-- Таблица: Sectors
DROP TABLE IF EXISTS Sectors;
CREATE TABLE IF NOT EXISTS Sectors (id_sector INTEGER PRIMARY KEY, sector TEXT);

-- Таблица: SecurityCollections
DROP TABLE IF EXISTS SecurityCollections;
CREATE TABLE IF NOT EXISTS SecurityCollections (collections_id INTEGER PRIMARY KEY, name TEXT (96), title TEXT (765), security_group_id INTEGER);

-- Таблица: SecurityGroups
DROP TABLE IF EXISTS SecurityGroups;
CREATE TABLE IF NOT EXISTS SecurityGroups (groups_id INTEGER PRIMARY KEY, name TEXT (93), title TEXT (765), is_hidden BOOLEAN);

-- Таблица: SecurityTypes
DROP TABLE IF EXISTS SecurityTypes;
CREATE TABLE IF NOT EXISTS SecurityTypes (id INTEGER PRIMARY KEY, engine_id INTEGER REFERENCES Engines (engine_id), security_type_name TEXT (93), security_type_title TEXT (765), security_group_name TEXT (93), stock_type TEXT (3));

-- Таблица: ShareDescriptions
DROP TABLE IF EXISTS ShareDescriptions;
CREATE TABLE IF NOT EXISTS ShareDescriptions (id_description INTEGER PRIMARY KEY, SECID TEXT, NAME TEXT, SHORTNAME TEXT, ISIN TEXT, REGNUMBER TEXT, ISSUESIZE INTEGER, FACEVALUE REAL, FACEUNIT TEXT, ISSUEDATE DATE, LISTLEVEL INTEGER, ISQUALIFIEDINVESTORS BOOL, MORNINGSESSION INTEGER, EVENINGSESSION INTEGER, WEEKENDSESSION INTEGER, TYPENAME TEXT, TYPE TEXT, EMITTER_ID INTEGER);

-- Таблица: SharesCollections
DROP TABLE IF EXISTS SharesCollections;
CREATE TABLE IF NOT EXISTS SharesCollections (SECID TEXT (36), ISSUENAME TEXT, NAME TEXT, SHORTNAME TEXT, ISIN TEXT (36), REGNUMBER TEXT (63), ISSUESIZE INTEGER, FACEVALUE REAL, FACEUNIT TEXT (9), ISSUEDATE DATE, LATNAME TEXT, HASPROSPECTUS INTEGER, EMITENTMISMATCHFIRST INTEGER, EMITENTMISMATCHCUR INTEGER, LISTLEVEL INTEGER, INCLUDEDBYMOEX INTEGER, ISQUALIFIEDINVESTORS INTEGER, QUALINVESTORGROUP TEXT, SHARESPERRECEIPT REAL, MORNINGSESSION INTEGER, EVENINGSESSION INTEGER, WEEKENDSESSION INTEGER, HIGHRISK INTEGER, TYPE TEXT, TYPENAME TEXT, IS_TRADED INTEGER, UPDATED_AT DATETIME);

-- Таблица: SharesMarketData
DROP TABLE IF EXISTS SharesMarketData;
CREATE TABLE IF NOT EXISTS SharesMarketData (
    i_data    INTEGER    PRIMARY KEY,
    SECID TEXT,
    BOARDID TEXT, 	
    BID REAL, 	
    BIDDEPTH TEXT, 	
    OFFER REAL, 	
    OFFERDEPTH TEXT, 	
    SPREAD REAL, 	
    BIDDEPTHT INTEGER, 	
    OFFERDEPTHT INTEGER, 	
    OPEN REAL, 	
    LOW REAL, 	
    HIGH REAL, 	
    [LAST] REAL, 	
    LASTCHANGE REAL, 	
    LASTCHANGEPRCNT REAL, 	
    QTY INTEGER, 	
    VALUE REAL, 	
    VALUE_USD REAL, 	
    WAPRICE REAL, 	
    LASTCNGTOLASTWAPRICE REAL, 	
    WAPTOPREVWAPRICEPRCNT REAL, 	
    WAPTOPREVWAPRICE REAL, 	
    CLOSEPRICE REAL, 	
    MARKETPRICETODAY REAL, 	
    MARKETPRICE REAL, 	
    LASTTOPREVPRICE REAL, 	
    NUMTRADES INTEGER, 	
    VOLTODAY INTEGER, 
    VALTODAY INTEGER, 	
    VALTODAY_USD INTEGER, 	
    ETFSETTLEPRICE REAL, 	
    TRADINGSTATUS TEXT, 	
    UPDATETIME DATE, 	
    LASTBID TEXT, 	
    LASTOFFER TEXT, 	
    LCLOSEPRICE REAL, 	
    LCURRENTPRICE REAL, 	
    MARKETPRICE2 REAL, 	
    NUMBIDS TEXT, 	
    NUMOFFERS TEXT, 	
    CHANGE REAL, 	
    TIME DATE, 	
    HIGHBID TEXT, 	
    LOWOFFER TEXT, 	
    PRICEMINUSPREVWAPRICE REAL, 	
    OPENPERIODPRICE REAL,	
    SEQNUM INTEGER, 	
    SYSTIME DATE, 	
    CLOSINGAUCTIONPRICE REAL, 	
    CLOSINGAUCTIONVOLUME REAL, 	
    ISSUECAPITALIZATION REAL, 
    ISSUECAPITALIZATION_UPDATETIME DATE, 
    ETFSETTLECURRENCY TEXT, 
    VALTODAY_RUR INTEGER, 
    TRADINGSESSION TEXT, 
    TRENDISSUECAPITALIZATION REAL
);

-- Таблица: SharesSecurities
DROP TABLE IF EXISTS SharesSecurities;
CREATE TABLE IF NOT EXISTS SharesSecurities (SECID TEXT (36), BOARDID TEXT (12), SHORTNAME TEXT (30), PREVPRICE REAL, LOTSIZE INTEGER, FACEVALUE REAL, STATUS TEXT (3), BOARDNAME TEXT, DECIMALS INTEGER, SECNAME TEXT (90), REMARKS TEXT (24), MARKETCODE TEXT (12), INSTRID TEXT (12), SECTORID TEXT (12), MINSTEP REAL, PREVWAPRICE REAL, FACEUNIT TEXT (12), PREVDATE DATE, ISSUESIZE INTEGER, ISIN TEXT (36), LATNAME TEXT (90), REGNUMBER TEXT (90), PREVLEGALCLOSEPRICE REAL, CURRENCYID TEXT (12), SECTYPE TEXT (12), LISTLEVEL INTEGER, SETTLEDATE DATE);

-- Таблица: Tools
DROP TABLE IF EXISTS Tools;
CREATE TABLE IF NOT EXISTS Tools (tool_id INTEGER PRIMARY KEY, tool_type TEXT);

-- Таблица: UpdateData
DROP TABLE IF EXISTS UpdateData;
CREATE TABLE IF NOT EXISTS UpdateData (date DATE, time TIME, id);

-- Таблица: YieldCurve
DROP TABLE IF EXISTS YieldCurve;
CREATE TABLE IF NOT EXISTS YieldCurve (id_data INTEGER PRIMARY KEY, tradedate TEXT, tradetime TEXT, B1 REAL, B2 REAL, B3 REAL, T1 REAL, G1 REAL, G2 REAL, G3 REAL, G4 REAL, G5 REAL, G6 REAL, G7 REAL, G8 REAL, G9 REAL);

-- Представление: BondView
DROP VIEW IF EXISTS BondView;
CREATE VIEW IF NOT EXISTS BondView AS SELECT BondsSecurities.SECID,
       BondsSecurities.ISIN, 
       BondsSecurities.SHORTNAME, 
       BondsSecurities.MATDATE, 
       BondsSecurities.PREVPRICE, 
       BondsSecurities.YIELDATPREVWAPRICE,
       BondsMarketData.EFFECTIVEYIELD, 
       BondsSecurities.COUPONPERCENT, 
       BondsSecurities.COUPONVALUE, 
       BondsSecurities.ACCRUEDINT, 
       BondsSecurities.NEXTCOUPON,
       BondsSecurities.COUPONPERIOD, 
       BondDescription.INITIALFACEVALUE, 
       BondDescription.FACEVALUE, 
       BondDescription.FACEUNIT, 
       BondsSecurities.LISTLEVEL, 
       BondDescription.EMITTER
    FROM BondsSecurities
        JOIN BondDescription
        ON BondDescription.SECID=BondsSecurities.SECID
        JOIN BondsMarketData
        ON BondsMarketData.SECID=BondsSecurities.SECID
    WHERE BondDescription.ISQUALIFIEDINVESTORS=0
        AND BondDescription.FACEUNIT='SUR'
        AND BondsSecurities.PREVPRICE is not NULL
        AND BondsSecurities.OFFERDATE is NULL
        AND BondsSecurities.COUPONPERCENT>1
        AND BondsSecurities.MATDATE>DATE('now')
        AND BondDescription.INITIALFACEVALUE=BondDescription.FACEVALUE
        AND BondDescription.EMITTER not like "%икрофинансовая%"
        AND BondDescription.EMITTER not like "%коллектор%"
        AND BondDescription.EMITTER not like "ООО %"
        AND BondsSecurities.SECNAME not like "%ОФЗ-АД%"
        AND BondsSecurities.SECNAME not like "%ОФЗ-ПК%"
        AND BondsSecurities.SECNAME not like "%ОФЗ-ИН%"
        AND BondsSecurities.BONDTYPE like "Фикс с известным купоном"
    GROUP BY BondsSecurities.MATDATE;

-- Представление: ОФЗ
DROP VIEW IF EXISTS ОФЗ;
CREATE VIEW IF NOT EXISTS ОФЗ AS SELECT SHORTNAME, PREVLEGALCLOSEPRICE, PREVDATE, YIELDATPREVWAPRICE, COUPONVALUE, NEXTCOUPON, ACCRUEDINT, PREVPRICE, FACEVALUE, MATDATE, COUPONPERIOD, FACEUNIT, CURRENCYID, ISSUESIZEPLACED, COUPONPERCENT, SETTLEDATE, LOTVALUE FROM BondsSecurities WHERE SHORTNAME LIKE ('ОФЗ' || '%') AND COUPONVALUE <> 0 AND MATDATE > DATE('now') GROUP BY MATDATE;

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
